FROM centos
MAINTAINER datawarehouse <aus-eng-data-warehouse@rmn.com>

RUN yum update -y
RUN yum install epel-release -y
RUN yum install -y \
    vim-enhanced \
    mlocate \
    git \
    python-pip \
    python-devel \
    postgres-devel \
    postgres-contrib \
    libpqxx-devel \
    wget


RUN mkdir -p /home/root
RUN cd /home/root
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN /usr/local/bin/pip install awscli

RUN yum install -y \
    libxml2-devel \
    xmlsec1-devel \
    xmlsec1-openssl-devel \
    libtool-ltdl-devel \
    ibxml2 \
    libxslt


ADD /src/python/requirements.txt /src/python/requirements.txt

RUN pip install -r /src/python/requirements.txt

# see https://github.com/onelogin/python-saml/issues/30 \
RUN if [ -f /usr/bin/xmlsec1-config ]; then  sed -i 's/the_flags="$the_flags  -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -I\/usr\/include\/xmlsec1   $the_xml_flags $the_xslt_flags $the_crypto_flags"/the_flags="$the_flags  -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -DXMLSEC_NO_SIZE_T -I\/usr\/include\/xmlsec1   $the_xml_flags $the_xslt_flags $the_crypto_flags"/g' /usr/bin/xmlsec1-config ; fi
RUN pip uninstall -y dm.xmlsec.binding
RUN pip install dm.xmlsec.binding

ADD src/python /src/python

RUN mkdir -p /mnt/docker-volumes/dart-web-static
RUN cp -rp /src/python/dart/web/ui/dist/* /mnt/docker-volumes/dart-web-static/
VOLUME /mnt/docker-volumes

WORKDIR /src/python/dart/web

ENV PYTHONPATH=/src/python:${PYTHONPATH}

EXPOSE 9191

CMD ["uwsgi", "--ini", "/src/python/dart/web/uwsgi.ini"]
